//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DataDictionary", typeof(DataDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Type.
        /// </summary>
        public static string AccessType {
            get {
                return ResourceManager.GetString("AccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acivities List.
        /// </summary>
        public static string ActivitiesList {
            get {
                return ResourceManager.GetString("ActivitiesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity indicator.
        /// </summary>
        public static string ActivityIndicator {
            get {
                return ResourceManager.GetString("ActivityIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity indicator list.
        /// </summary>
        public static string ActivityIndicatorList {
            get {
                return ResourceManager.GetString("ActivityIndicatorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Plan.
        /// </summary>
        public static string ActivityPlan {
            get {
                return ResourceManager.GetString("ActivityPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Plan List.
        /// </summary>
        public static string ActivityPlansList {
            get {
                return ResourceManager.GetString("ActivityPlansList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Plan Summary.
        /// </summary>
        public static string ActivityPlanSummary {
            get {
                return ResourceManager.GetString("ActivityPlanSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivityProduct.
        /// </summary>
        public static string ActivityProduct {
            get {
                return ResourceManager.GetString("ActivityProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Log Input Parameters.
        /// </summary>
        public static string AllowLogInputParameters {
            get {
                return ResourceManager.GetString("AllowLogInputParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Log Output Parameters.
        /// </summary>
        public static string AllowLogOutputParameters {
            get {
                return ResourceManager.GetString("AllowLogOutputParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string Alreadyhaveanaccount {
            get {
                return ResourceManager.GetString("Alreadyhaveanaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string ApplicationEntity {
            get {
                return ResourceManager.GetString("ApplicationEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Type.
        /// </summary>
        public static string ApplicationEntityType {
            get {
                return ResourceManager.GetString("ApplicationEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Group.
        /// </summary>
        public static string ApplicationGroup {
            get {
                return ResourceManager.GetString("ApplicationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application IP.
        /// </summary>
        public static string ApplicationIP {
            get {
                return ResourceManager.GetString("ApplicationIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Evaluation System(MANA).
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Url.
        /// </summary>
        public static string ApplicationUrl {
            get {
                return ResourceManager.GetString("ApplicationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business List.
        /// </summary>
        public static string BusinessList {
            get {
                return ResourceManager.GetString("BusinessList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type.
        /// </summary>
        public static string BusinessType {
            get {
                return ResourceManager.GetString("BusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Types List.
        /// </summary>
        public static string BusinessTypesList {
            get {
                return ResourceManager.GetString("BusinessTypesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity level.
        /// </summary>
        public static string Capacitylevel {
            get {
                return ResourceManager.GetString("Capacitylevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Phone Number.
        /// </summary>
        public static string CellPhoneNumber {
            get {
                return ResourceManager.GetString("CellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Use.
        /// </summary>
        public static string ChangeUse {
            get {
                return ResourceManager.GetString("ChangeUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies List.
        /// </summary>
        public static string CompaniesList {
            get {
                return ResourceManager.GetString("CompaniesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Category.
        /// </summary>
        public static string CompanyCategory {
            get {
                return ResourceManager.GetString("CompanyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Parent.
        /// </summary>
        public static string CompanyParent {
            get {
                return ResourceManager.GetString("CompanyParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Type.
        /// </summary>
        public static string CompanyType {
            get {
                return ResourceManager.GetString("CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture Id.
        /// </summary>
        public static string CultureId {
            get {
                return ResourceManager.GetString("CultureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactive.
        /// </summary>
        public static string Deactive {
            get {
                return ResourceManager.GetString("Deactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Date.
        /// </summary>
        public static string DeleteDate {
            get {
                return ResourceManager.GetString("DeleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Number.
        /// </summary>
        public static string DocNumber {
            get {
                return ResourceManager.GetString("DocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Place.
        /// </summary>
        public static string DocPlace {
            get {
                return ResourceManager.GetString("DocPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economic Code.
        /// </summary>
        public static string EconomicCode {
            get {
                return ResourceManager.GetString("EconomicCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Path Name.
        /// </summary>
        public static string EntityPathName {
            get {
                return ResourceManager.GetString("EntityPathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date Time.
        /// </summary>
        public static string ExpireDateTime {
            get {
                return ResourceManager.GetString("ExpireDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldCode.
        /// </summary>
        public static string FieldCode {
            get {
                return ResourceManager.GetString("FieldCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Price.
        /// </summary>
        public static string FinalPrice {
            get {
                return ResourceManager.GetString("FinalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast Final Price.
        /// </summary>
        public static string ForecastFinalPrice {
            get {
                return ResourceManager.GetString("ForecastFinalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast Incom.
        /// </summary>
        public static string ForecastIncom {
            get {
                return ResourceManager.GetString("ForecastIncom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast Level.
        /// </summary>
        public static string ForecastLevel {
            get {
                return ResourceManager.GetString("ForecastLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast Production.
        /// </summary>
        public static string ForecastProduction {
            get {
                return ResourceManager.GetString("ForecastProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast Sales.
        /// </summary>
        public static string ForecastSales {
            get {
                return ResourceManager.GetString("ForecastSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Program.
        /// </summary>
        public static string FutureProgram {
            get {
                return ResourceManager.GetString("FutureProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Profit.
        /// </summary>
        public static string GrossProfit {
            get {
                return ResourceManager.GetString("GrossProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World!.
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Parameters.
        /// </summary>
        public static string InputParameters {
            get {
                return ResourceManager.GetString("InputParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Date.
        /// </summary>
        public static string InsertDate {
            get {
                return ResourceManager.GetString("InsertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string InsertDateTime {
            get {
                return ResourceManager.GetString("InsertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expirable.
        /// </summary>
        public static string IsExpirable {
            get {
                return ResourceManager.GetString("IsExpirable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is IP Restricted.
        /// </summary>
        public static string IsIPRestricted {
            get {
                return ResourceManager.GetString("IsIPRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string IsSuccessful {
            get {
                return ResourceManager.GetString("IsSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synced.
        /// </summary>
        public static string IsSynced {
            get {
                return ResourceManager.GetString("IsSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Url Restricted.
        /// </summary>
        public static string IsUrlRestricted {
            get {
                return ResourceManager.GetString("IsUrlRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string IsVerified {
            get {
                return ResourceManager.GetString("IsVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Tag.
        /// </summary>
        public static string LanguageTag {
            get {
                return ResourceManager.GetString("LanguageTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Product.
        /// </summary>
        public static string ManageProduct {
            get {
                return ResourceManager.GetString("ManageProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        public static string Metric {
            get {
                return ResourceManager.GetString("Metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric List.
        /// </summary>
        public static string MetricList {
            get {
                return ResourceManager.GetString("MetricList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Million Rials.
        /// </summary>
        public static string MillionRials {
            get {
                return ResourceManager.GetString("MillionRials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Code.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opposition.
        /// </summary>
        public static string Opposition {
            get {
                return ResourceManager.GetString("Opposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordering.
        /// </summary>
        public static string Ordering {
            get {
                return ResourceManager.GetString("Ordering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Parameters.
        /// </summary>
        public static string OutputParameters {
            get {
                return ResourceManager.GetString("OutputParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership.
        /// </summary>
        public static string Ownership {
            get {
                return ResourceManager.GetString("Ownership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage Of Sales Share.
        /// </summary>
        public static string PercentageOfSalesShare {
            get {
                return ResourceManager.GetString("PercentageOfSalesShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Type.
        /// </summary>
        public static string PhoneNumberType {
            get {
                return ResourceManager.GetString("PhoneNumberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Base Form.
        /// </summary>
        public static string PlanBaseForm {
            get {
                return ResourceManager.GetString("PlanBaseForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan checkout.
        /// </summary>
        public static string PlanCheckout {
            get {
                return ResourceManager.GetString("PlanCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan List.
        /// </summary>
        public static string PlanList {
            get {
                return ResourceManager.GetString("PlanList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Title.
        /// </summary>
        public static string PlanTitle {
            get {
                return ResourceManager.GetString("PlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Business.
        /// </summary>
        public static string PrincipalBusiness {
            get {
                return ResourceManager.GetString("PrincipalBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prinsipal Business List.
        /// </summary>
        public static string PrinsipalBusinessList {
            get {
                return ResourceManager.GetString("PrinsipalBusinessList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Activity Plan List.
        /// </summary>
        public static string ProductActivityPlanList {
            get {
                return ResourceManager.GetString("ProductActivityPlanList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product indicator.
        /// </summary>
        public static string ProductIndicator {
            get {
                return ResourceManager.GetString("ProductIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product indicator list.
        /// </summary>
        public static string ProductIndicatorList {
            get {
                return ResourceManager.GetString("ProductIndicatorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product list.
        /// </summary>
        public static string ProductList {
            get {
                return ResourceManager.GetString("ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Plan.
        /// </summary>
        public static string ProductPlan {
            get {
                return ResourceManager.GetString("ProductPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer.
        /// </summary>
        public static string Programmer {
            get {
                return ResourceManager.GetString("Programmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register IP.
        /// </summary>
        public static string RegisterIP {
            get {
                return ResourceManager.GetString("RegisterIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        public static string RegistrationNumber {
            get {
                return ResourceManager.GetString("RegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection.
        /// </summary>
        public static string Rejection {
            get {
                return ResourceManager.GetString("Rejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Count.
        /// </summary>
        public static string RequestCount {
            get {
                return ResourceManager.GetString("RequestCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        public static string RequestType {
            get {
                return ResourceManager.GetString("RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rials.
        /// </summary>
        public static string Rials {
            get {
                return ResourceManager.GetString("Rials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows per page:.
        /// </summary>
        public static string RowsPerPage {
            get {
                return ResourceManager.GetString("RowsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salability.
        /// </summary>
        public static string Salability {
            get {
                return ResourceManager.GetString("Salability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Per Product Unit.
        /// </summary>
        public static string SalePerProductUnit {
            get {
                return ResourceManager.GetString("SalePerProductUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil Texture.
        /// </summary>
        public static string SoilTexture {
            get {
                return ResourceManager.GetString("SoilTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super User.
        /// </summary>
        public static string SuperUser {
            get {
                return ResourceManager.GetString("SuperUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Expire Date Time.
        /// </summary>
        public static string TokenExpireDateTime {
            get {
                return ResourceManager.GetString("TokenExpireDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Area.
        /// </summary>
        public static string TotalArea {
            get {
                return ResourceManager.GetString("TotalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sales.
        /// </summary>
        public static string TotalSales {
            get {
                return ResourceManager.GetString("TotalSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Township.
        /// </summary>
        public static string Township {
            get {
                return ResourceManager.GetString("Township", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Conversion.
        /// </summary>
        public static string UnitConversion {
            get {
                return ResourceManager.GetString("UnitConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Conversion IntoTon.
        /// </summary>
        public static string UnitConversionIntoTon {
            get {
                return ResourceManager.GetString("UnitConversionIntoTon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateDateTime {
            get {
                return ResourceManager.GetString("UpdateDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usable Area.
        /// </summary>
        public static string UsableArea {
            get {
                return ResourceManager.GetString("UsableArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User IP.
        /// </summary>
        public static string UserIP {
            get {
                return ResourceManager.GetString("UserIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifier User.
        /// </summary>
        public static string VerifierUser {
            get {
                return ResourceManager.GetString("VerifierUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Date Time.
        /// </summary>
        public static string VerifyDateTime {
            get {
                return ResourceManager.GetString("VerifyDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
