//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LinkCaptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LinkCaptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LinkCaptions", typeof(LinkCaptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Activities/Index.
        /// </summary>
        public static string Activities_Index {
            get {
                return ResourceManager.GetString("Activities-Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Activity/Create.
        /// </summary>
        public static string Activity_Create {
            get {
                return ResourceManager.GetString("Activity-Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Activity/Edit.
        /// </summary>
        public static string Activity_Edit {
            get {
                return ResourceManager.GetString("Activity-Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ActivityIndicator/Create.
        /// </summary>
        public static string ActivityIndicator_Create {
            get {
                return ResourceManager.GetString("ActivityIndicator-Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ActivityIndicator/Edit.
        /// </summary>
        public static string ActivityIndicator_Edit {
            get {
                return ResourceManager.GetString("ActivityIndicator-Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ActivityIndicators/Index.
        /// </summary>
        public static string ActivityIndicators_Index {
            get {
                return ResourceManager.GetString("ActivityIndicators-Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ActivityPlan/Create.
        /// </summary>
        public static string ActivityPlan_Create {
            get {
                return ResourceManager.GetString("ActivityPlan_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ActivityPlan/Edit.
        /// </summary>
        public static string ActivityPlan_Edit {
            get {
                return ResourceManager.GetString("ActivityPlan_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ActivityPlans/Index.
        /// </summary>
        public static string ActivityPlan_Index {
            get {
                return ResourceManager.GetString("ActivityPlan_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ActivityPlan/Summary.
        /// </summary>
        public static string ActivityPlan_Summary {
            get {
                return ResourceManager.GetString("ActivityPlan_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ActivityProduct.
        /// </summary>
        public static string ActivityProduct {
            get {
                return ResourceManager.GetString("ActivityProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Business/Create.
        /// </summary>
        public static string Business_Create {
            get {
                return ResourceManager.GetString("Business-Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Business/Edit.
        /// </summary>
        public static string Business_Edit {
            get {
                return ResourceManager.GetString("Business-Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Business/Index.
        /// </summary>
        public static string Business_Index {
            get {
                return ResourceManager.GetString("Business-Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /BusinessType/Create.
        /// </summary>
        public static string BusinessType_Create {
            get {
                return ResourceManager.GetString("BusinessType-Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /BusinessType/Edit.
        /// </summary>
        public static string BusinessType_Edit {
            get {
                return ResourceManager.GetString("BusinessType-Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /BusinessTypes/Index.
        /// </summary>
        public static string BusinessType_Index {
            get {
                return ResourceManager.GetString("BusinessType-Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Companies/Index.
        /// </summary>
        public static string Companies_Index {
            get {
                return ResourceManager.GetString("Companies_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Company/Create.
        /// </summary>
        public static string Company_Create {
            get {
                return ResourceManager.GetString("Company_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Company/Edit.
        /// </summary>
        public static string Company_Edit {
            get {
                return ResourceManager.GetString("Company_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/ManaLogo.png.
        /// </summary>
        public static string ManaLogo {
            get {
                return ResourceManager.GetString("ManaLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Metric/Create.
        /// </summary>
        public static string Metric_Create {
            get {
                return ResourceManager.GetString("Metric-Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Metric/Edit.
        /// </summary>
        public static string Metric_Edit {
            get {
                return ResourceManager.GetString("Metric-Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Metrics/Index.
        /// </summary>
        public static string Metric_Index {
            get {
                return ResourceManager.GetString("Metric-Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Plan/Create.
        /// </summary>
        public static string Plan_Create {
            get {
                return ResourceManager.GetString("Plan_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Plan/Edit.
        /// </summary>
        public static string Plan_Edit {
            get {
                return ResourceManager.GetString("Plan_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Plans/Index.
        /// </summary>
        public static string Plans_Index {
            get {
                return ResourceManager.GetString("Plans_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PrincipalBusiness/create.
        /// </summary>
        public static string PrincipalBusiness_Create {
            get {
                return ResourceManager.GetString("PrincipalBusiness-Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PrincipalBusiness/Edit.
        /// </summary>
        public static string PrincipalBusiness_Edit {
            get {
                return ResourceManager.GetString("PrincipalBusiness-Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PrincipalBusiness/Index.
        /// </summary>
        public static string PrincipalBusiness_Index {
            get {
                return ResourceManager.GetString("PrincipalBusiness-Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Product/Create.
        /// </summary>
        public static string Product_Create {
            get {
                return ResourceManager.GetString("Product-Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Product/Edit.
        /// </summary>
        public static string Product_Edit {
            get {
                return ResourceManager.GetString("Product-Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ProductActivityPlan/Create.
        /// </summary>
        public static string ProductActivityPlan_Create {
            get {
                return ResourceManager.GetString("ProductActivityPlan_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ProductActivityPlan/Edit.
        /// </summary>
        public static string ProductActivityPlan_Edit {
            get {
                return ResourceManager.GetString("ProductActivityPlan_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ProductActivityPlans/Index.
        /// </summary>
        public static string ProductActivityPlans_Index {
            get {
                return ResourceManager.GetString("ProductActivityPlans_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ProductIndicator/Create.
        /// </summary>
        public static string ProductIndicator_Create {
            get {
                return ResourceManager.GetString("ProductIndicator-Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ProductIndicator/Edit.
        /// </summary>
        public static string ProductIndicator_Edit {
            get {
                return ResourceManager.GetString("ProductIndicator-Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ProductIndicators/Index.
        /// </summary>
        public static string ProductIndicators_Index {
            get {
                return ResourceManager.GetString("ProductIndicators-Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ProductPlan.
        /// </summary>
        public static string ProductPlan_Create {
            get {
                return ResourceManager.GetString("ProductPlan_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Products/Index.
        /// </summary>
        public static string Products_Index {
            get {
                return ResourceManager.GetString("Products-Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SuggestedPlan.
        /// </summary>
        public static string SuggestedPlan {
            get {
                return ResourceManager.GetString("SuggestedPlan", resourceCulture);
            }
        }
    }
}
